name: Trigger lib Api
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        #checkout repo code 
      - name: Check Out Repo 
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          token: ${{ secrets.TEST }}
      - name: Build Web App
        run: |  
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/theionSami/demo_lib_trigger_workflow/actions/lib_trigger.yml/dispatches  \
          -d '{"ref":"ref"}'
      - name: Build Web App
        run: |
          curl \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/theionSami/actions/secrets
      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          sleep 10s
