name: test_lib
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get workflow id by trigger
        run: |
          curl -i -H "Authorization: token ${{ secrets.TEST }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/theionSami/demo_lib_trigger_workflow/actions/workflows
